program VICRIS;

uses
  Forms,
  uBrowse in '..\..\FrameWork\Repository\uBrowse.pas' {fmBrowse: TfmRoot},
  udmBrowse in '..\..\FrameWork\DBSrc\udmBrowse.pas' {dmBrowse: TdmDBRoot},
  uEdit in '..\..\FrameWork\Repository\uEdit.pas' {fmEdit},
  udmEdit in '..\..\FrameWork\DBSrc\udmEdit.pas' {dmEdit: TdmDBRoot},
  udmEditAaa in '..\..\FrameWork\DBSrc\udmEditAaa.pas' {dmEditAaa: TdmDBRoot},
  uMlSearch in '..\..\FrameWork\Object\uMlSearch.pas' {fmMlSearch},
  udmChkUsr in '..\..\FrameWork\Object\udmChkUsr.pas' {dmChkUsr: TDataModule},
  uChkUsr in '..\..\FrameWork\Object\uChkUsr.pas' {fmChkUsr},
  uSupportLib in '..\..\SharedUnit\uSupportLib.pas',
  udmSearch in '..\Object\udmSearch.pas' {dmSearch: TDataModule},
  uMenu in '..\Src\uMenu.pas' {fmMenu},
  udmBrCliente in '..\DataModule\udmBrCliente.pas' {dmBrCliente: TdmDBRoot},
  uBrCliente in '..\Src\uBrCliente.pas' {fmBrCliente: TfmRoot},
  udmEdAutore in '..\DataModule\udmEdAutore.pas' {dmEdAutore: TdmDBRoot},
  uEdAutore in '..\Src\uEdAutore.pas' {fmEdAutore: TfmRoot},
  udmBrCollezione in '..\DataModule\udmBrCollezione.pas' {dmBrCollezione: TdmDBRoot},
  uBrCollezione in '..\Src\uBrCollezione.pas' {fmBrCollezione: TfmRoot},
  udmEdCollezione in '..\DataModule\udmEdCollezione.pas' {dmEdCollezione: TdmDBRoot},
  uEdCollezione in '..\Src\uEdCollezione.pas' {fmEdCollezione: TfmRoot},
  udmBrPromotore in '..\DataModule\udmBrPromotore.pas' {dmBrPromotore: TdmDBRoot},
  uBrPromotore in '..\Src\uBrPromotore.pas' {fmBrPromotore: TfmRoot},
  udmEdPromotore in '..\DataModule\udmEdPromotore.pas' {dmEdPromotore: TdmDBRoot},
  uEdPromotore in '..\Src\uEdPromotore.pas' {fmEdPromotore: TfmRoot},
  udmBrOggetto in '..\DataModule\udmBrOggetto.pas' {dmBrOggetto: TdmDBRoot},
  udmEdOggetto in '..\DataModule\udmEdOggetto.pas' {dmEdOggetto: TdmDBRoot},
  uBrOggetto in '..\Src\uBrOggetto.pas' {fmBrOggetto: TfmRoot},
  uEdOggetto in '..\Src\uEdOggetto.pas' {fmEdOggetto: TfmRoot},
  udmBrNazione in '..\DataModule\udmBrNazione.pas' {dmBrNazione: TdmDBRoot},
  udmEdNazione in '..\DataModule\udmEdNazione.pas' {dmEdNazione: TdmDBRoot},
  uBrNazione in '..\Src\uBrNazione.pas' {fmBrNazione: TfmRoot},
  uEdNazione in '..\Src\uEdNazione.pas' {fmEdNazione: TfmRoot},
  udmBrCitta in '..\DataModule\udmBrCitta.pas' {dmBrCitta: TdmDBRoot},
  uBrCitta in '..\Src\uBrCitta.pas' {fmBrCitta: TfmRoot},
  udmEdCitta in '..\DataModule\udmEdCitta.pas' {dmEdCitta: TdmDBRoot},
  uEdCitta in '..\Src\uEdCitta.pas' {fmEdCitta: TfmRoot},
  udmBrEditrice in '..\DataModule\udmBrEditrice.pas' {dmBrEditrice: TdmDBRoot},
  uBrEditrice in '..\Src\uBrEditrice.pas' {fmBrEditrice: TfmRoot},
  udmEdEditrice in '..\DataModule\udmEdEditrice.pas' {dmEdEditrice: TdmDBRoot},
  uEdEditrice in '..\Src\uEdEditrice.pas' {fmEdEditrice: TfmRoot},
  udmBrPubblicazione in '..\DataModule\udmBrPubblicazione.pas' {dmBrPubblicazione: TdmDBRoot},
  uBrPubblicazione in '..\Src\uBrPubblicazione.pas' {fmBrPubblicazione: TfmRoot},
  udmEdPubblicazione in '..\DataModule\udmEdPubblicazione.pas' {dmEdPubblicazione: TdmDBRoot},
  uEdPubblicazione in '..\Src\uEdPubblicazione.pas' {fmEdPubblicazione: TfmRoot},
  udmGlobal in '..\..\SharedUnit\udmGlobal.pas' {dmGlobal: TDataModule},
  uGlobals in '..\..\SharedUnit\uGlobals.pas',
  uAbout in '..\Src\uAbout.pas' {fmAbout},
  udmBrIncarico in '..\DataModule\udmBrIncarico.pas' {dmBrIncarico: TdmDBRoot},
  uBrIncarico in '..\Src\uBrIncarico.pas' {fmBrIncarico: TfmRoot},
  udmEdIncarico in '..\DataModule\udmEdIncarico.pas' {dmEdIncarico: TdmDBRoot},
  uEdIncarico in '..\Src\uEdIncarico.pas' {fmEdIncarico: TfmRoot},
  udmBrPersona in '..\DataModule\udmBrPersona.pas' {dmBrPersona: TdmDBRoot},
  uBrPersona in '..\Src\uBrPersona.pas' {fmBrPersona: TfmRoot},
  udmEdPersona in '..\DataModule\udmEdPersona.pas' {dmEdPersona: TdmDBRoot},
  uEdPersona in '..\Src\uEdPersona.pas' {fmEdPersona: TfmRoot},
  udmBrRuolo in '..\DataModule\udmBrRuolo.pas' {dmBrRuolo: TdmDBRoot},
  uBrRuolo in '..\Src\uBrRuolo.pas' {fmBrRuolo: TfmRoot},
  udmEdRuolo in '..\DataModule\udmEdRuolo.pas' {dmEdRuolo: TdmDBRoot},
  uEdRuolo in '..\Src\uEdRuolo.pas' {fmEdRuolo: TfmRoot},
  udmBrProtocollo in '..\DataModule\udmBrProtocollo.pas' {dmBrProtocollo: TdmDBRoot},
  uBrProtocollo in '..\Src\uBrProtocollo.pas' {fmBrProtocollo: TfmRoot},
  udmEdProtocollo in '..\DataModule\udmEdProtocollo.pas' {dmEdProtocollo: TdmDBRoot},
  uEdProtocollo in '..\Src\uEdProtocollo.pas' {fmEdProtocollo: TfmRoot},
  udmBrUbi in '..\DataModule\udmBrUbi.pas' {dmBrUbi: TdmDBRoot},
  uBrUbi in '..\Src\uBrUbi.pas' {fmBrUbi: TfmRoot},
  udmEdUbi in '..\DataModule\udmEdUbi.pas' {dmEdUbi: TdmDBRoot},
  uEdUbi in '..\Src\uEdUbi.pas' {fmEdUbi: TfmRoot},
  udmBrEvento in '..\DataModule\udmBrEvento.pas' {dmBrEvento: TdmDBRoot},
  udmEdEvento in '..\DataModule\udmEdEvento.pas' {dmEdEvento: TdmDBRoot},
  uBrEvento in '..\Src\uBrEvento.pas' {fmBrEvento: TfmRoot},
  uEdEvento in '..\Src\uEdEvento.pas' {fmEdEvento: TfmRoot},
  udmBrAlarma in '..\DataModule\udmBrAlarma.pas' {dmBrAlarma: TdmDBRoot},
  uBrAlarma in '..\Src\uBrAlarma.pas' {fmBrAlarma: TfmRoot},
  udmEdAlarma in '..\DataModule\udmEdAlarma.pas' {dmEdAlarma: TdmDBRoot},
  uEdAlarma in '..\Src\uEdAlarma.pas' {fmEdAlarma: TfmRoot};

{$R *.res}

begin
  Application.Initialize;
  Application.Title := 'VICRIS';
  Application.CreateForm(TfmMenu, fmMenu);
  Application.Run;
end.
